dist: bionic
language: ruby
cache: bundler
rvm:
  # Possibly https://github.com/travis-ci/travis-ci/issues/2220
  - 2.1.10
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

matrix:
  allow_failures:
  # We build ruby-head using docker, but maybe this will start working again
  # on Travis CI.
    - rvm: ruby-head

services:
  - docker

jobs:
  include:
    - stage: ruby-head
      env: RVM_RUBY_VERSION=ruby-head
      before_install:
        - sudo docker build -t stackprof-$RVM_RUBY_VERSION --build-arg=RVM_RUBY_VERSION=$RVM_RUBY_VERSION .
      script:
        - sudo docker run --name stackprof-$RVM_RUBY_VERSION stackprof-$RVM_RUBY_VERSION
